first_django_project/first_django_project/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('hello/',include("hello.urls")),
    path('newyear/',include("newyear.urls")),
    path('todolist/',include("todolist.urls"))
]

first_django_project/hello/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path("",views.index,name="index"),
    path("<str:name>",views.greet,name="greet")
]

first_django_project/newyear/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path("",views.index,name="index")
]

first_django_project/todolist/urls.py
from django.urls import path
from . import views
app_name="todolist"
urlpatterns=[
    path("",views.index,name="index"),
    path("add",views.addtask,name="add")
]

first_django_project/hello/models.py
from django.db import models

# Create your models here.

first_django_project/newyear/models.py
from django.db import models

# Create your models here.

first_django_project/todolist/models.py
from django.db import models

# Create your models here.

first_django_project/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    # return HttpResponse("Hello")
    return render(request,"hello/index.html")
# def greet(request,name):
#     return HttpResponse(f"Hello, {name.capitalize()}")
def greet(request,name):
    return render(request,"hello/greet.html",{
        "name":name.capitalize()
    })

first_django_project/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now=datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "newyear":now.month==1 and now.day==1
        # "newyear":True
    })

first_django_project/todolist/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render
# tasks=[]
class NewTaskForm(forms.Form):
    task=forms.CharField(label="New Task")
    priority=forms.IntegerField(label="Priority", min_value=1,max_value=5)
# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"]=[]
    return render(request,"todolist/index.html",{
        "tasks":request.session["tasks"]
    })
def addtask(request):
    if request.method=="POST":
        form=NewTaskForm(request.POST) #populates this form with all of the data user has entered
        if form.is_valid():
            task=form.cleaned_data["task"]
            request.session["tasks"]+=[task]
            return HttpResponseRedirect(reverse("todolist:index"))
        else:
            return render(request,"todolist/add.html",{
                "form":form
            })
        
    return render(request,"todolist/add.html",{
        "form":NewTaskForm
    })

first_django_project/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Hi there {{name}}</h2>
</body>
</html>

first_django_project/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hiiiii</h1>
</body>
</html>

first_django_project/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it New Years?</title>
    <link rel="stylesheet" href="{% static 'newyear/style.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

first_django_project/todolist/templates/todolist/add.html
{% extends "todolist/layout.html" %}
{% block body %}
    <form action="{% url 'todolist:add' %}" method="post">
        {% csrf_token %}
        <h1>Add task</h1>
       {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'todolist:index' %}">View task</a>
{% endblock %}
    

first_django_project/todolist/templates/todolist/index.html
{% extends "todolist/layout.html" %}
{% block body %}
<h1>Tasks</h1>
<ul>
    {% for task in tasks %}
    <li>{{task}}</li>
    {% empty %}
    <li>No tasks.</li>
    {% endfor %}
</ul>
<a href="{% url 'todolist:add' %}">Add a new task</a>
{% endblock %}

first_django_project/todolist/templates/todolist/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>